export const products = [
  {
    id: 1,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "A&W Cream Soda",
    descripcion: "Lata - 355 ml",
    precio: 80,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/cream_soda_l6coup.webp",
  },
  {
    id: 2,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "A&W Root Beer",
    descripcion: "Lata - 355 ml",
    precio: 80,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/root_bear_eopbcf.webp",
  },
  {
    id: 3,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "Coca Cola Original",
    descripcion: "Lata - 355 ml",
    precio: 40,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/coca_cola_jc3njo.webp",
  },
  {
    id: 4,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "Snapple Limón Light",
    descripcion: "Botella - 473 ml",
    precio: 40,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/snapple_limon_light_tzypax.webp",
  },
  {
    id: 5,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "Boing Mango",
    descripcion: "Botella - 355 ml",
    precio: 35,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/boing_mango_sxytxl.webp",
  },
  {
    id: 6,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "Sidral Mundet",
    descripcion: "Lata - 355 ml",
    precio: 35,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/sidral_mundet_jydcpt.webp",
  },
  {
    id: 7,
    tipo: "Bebidas",
    categoria: "Refrescos",
    nombre: "Agua Mineral Peñafiel",
    descripcion: "Lata - 355 ml",
    precio: 30,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568351/agua_mineral_pe%C3%B1afiel_u9kzex.webp",
  },
  {
    id: 8,
    tipo: "Bebidas",
    categoria: "Cocteleria",
    nombre: "Poblanito",
    descripcion: "",
    precio: 125,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568387/poblanito_hcvwa3.webp",
  },
  {
    id: 9,
    tipo: "Bebidas",
    categoria: "Cocteleria",
    nombre: "Beso de Sabina",
    descripcion: "",
    precio: 145,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568387/beso_de_sabina_ytpqup.webp",
  },
  {
    id: 10,
    tipo: "Bebidas",
    categoria: "Cocteleria",
    nombre: "Mojito",
    descripcion: "",
    precio: 100,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568387/mojito_eyhkwg.webp",
  },
  {
    id: 11,
    tipo: "Bebidas",
    categoria: "Cocteleria",
    nombre: "Carajillo",
    descripcion: "",
    precio: 100,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568388/carajillo_oafkh9.webp",
  },
  {
    id: 12,
    tipo: "Bebidas",
    categoria: "Cocteleria",
    nombre: "Gin Tónico",
    descripcion: "",
    precio: 165,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568387/gin_tonico_nhbyqm.webp",
  },
  {
    id: 13,
    tipo: "Bebidas",
    categoria: "Cervezas",
    nombre: "Heineken",
    descripcion: "355 ml",
    precio: 65,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568419/heineken_v44siz.webp",
  },
  {
    id: 14,
    tipo: "Bebidas",
    categoria: "Cervezas",
    nombre: "Bohemia Pilsner",
    descripcion: "355 ml",
    precio: 55,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568419/bohemia_pilsner_tlztte.webp",
  },
  {
    id: 15,
    tipo: "Bebidas",
    categoria: "Cervezas",
    nombre: "Nochebuena",
    descripcion: "355 ml",
    precio: 60,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568419/nochebuena_ns42gg.webp",
  },
  {
    id: 16,
    tipo: "Bebidas",
    categoria: "Cervezas",
    nombre: "Ticus Porter",
    descripcion: "355 ml",
    precio: 140,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568419/Ticus_Porter_i6tor5.webp",
  },
  {
    id: 17,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Ron Bacardi Blanco",
    descripcion: "Copa 2 oz",
    precio: 50,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568442/bacardi_blanco_d5zqaa.webp"
  },
  {
    id: 18,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Ron Abuelo",
    descripcion: "Copa 2 oz",
    precio: 60,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568442/abuelo_sa3ygx.webp",
  },
  {
    id: 19,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Whiskey Jack Daniel's 7",
    descripcion: "Copa 2 oz",
    precio: 125,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568442/jack_daniels_7_b9y7sy.webp",
  },
  {
    id: 20,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Mezcal 400 conejos",
    descripcion: "Copa 2 oz",
    precio: 160,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568463/400_conejos_lva7o3.webp",
  },
  {
    id: 21,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Gin Bombay Sapphire",
    descripcion: "Copa 2 oz",
    precio: 140,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568463/bombay_sapphire_pa5gia.webp",
  },
  {
    id: 22,
    tipo: "Bebidas",
    categoria: "Bebidas_Alcoholicas",
    nombre: "Tequila 1800 Reposado",
    descripcion: "Copa 2 oz",
    precio: 150,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568463/1800_reposado_jma82n.webp",
  },
  {
    id: 23,
    tipo: "Alimentos",
    categoria: "BBQ",
    nombre: "BBQ Sampler",
    descripcion:
      "Mezcla de nuestras tres principales carnes ahumadas (Pork Ribs, Brisket y Pulled Pork) acompañadas de tres Texas Toast",
    precio: 415,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568495/BBQ_Sampler_ltwuy1.webp",
  },
  {
    id: 24,
    tipo: "Alimentos",
    categoria: "BBQ",
    nombre: "Brisket",
    descripcion:
      "Pecho de res ahumado y endulzado con nuestra Smokes BBQ Sauce. Incluye un Texas Toast",
    precio: 235,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568497/Brisket_w3fmfb.webp",
  },
  {
    id: 25,
    tipo: "Alimentos",
    categoria: "BBQ",
    nombre: "Pulled Pork",
    descripcion:
      "Espaldilla de cerdo ahumada y bañada en nuestra Smokes BBQ Sauce. Incluye un Texas Toast.",
    precio: 195,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568495/Pulled_Pork_grugcu.webp",
  },
  {
    id: 26,
    tipo: "Alimentos",
    categoria: "BBQ",
    nombre: "Fat Bastard's Ribs",
    descripcion:
      "Costillas de hombro de cerdo ahumadas y bañadas en Smokes BBQ Sauce. Incluye un Texas Toast.",
    precio: 270,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568495/Fat_Bastard_Ribs_brchuw.webp",
  },
  {
    id: 27,
    tipo: "Alimentos",
    categoria: "BBQ",
    nombre: "Turkey Leg",
    descripcion:
      "Pierna de pavo con doble ahumado, servida con salsa de arándano y cereza. Incluye un Texas Toast.",
    precio: 490,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568497/Turkey_Leg_hzun82.webp",
  },
  {
    id: 28,
    tipo: "Alimentos",
    categoria: "Sandwiches",
    nombre: "Brisket Sandwich",
    descripcion:
      "Sandwich de pecho de res ahumado y caramelizado con Smokes BBQ Sauce dentro de un bollo americano",
    precio: 180,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568521/Brisket_Sandwich_txs9vd.webp",
  },
  {
    id: 29,
    tipo: "Alimentos",
    categoria: "Sandwiches",
    nombre: "Pulled Pork Sandwich",
    descripcion:
      "Sandiwch de espaldilla de cerdo ahumada y bañada en Smokes BBQ Sauce dentro de un bollo americano",
    precio: 155,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568522/Pulled_Pork_Sandwich_miyab7.webp",
  },
  {
    id: 30,
    tipo: "Alimentos",
    categoria: "Sandwiches",
    nombre: "Rib Sandiwch",
    descripcion:
      "Sandwich de costilla de cerdo ahumada y bañada con Smokes BBQ Sauce, chicharrón de queso gouda, cebolla caramelizada, Mayo Chipotle y chile jalapeño a la sal dentro de Pan Pretzel",
    precio: 245,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568522/Rib_Sandwich_wuagod.webp",
  },
  {
    id: 31,
    tipo: "Alimentos",
    categoria: "Sides",
    nombre: "MVP Fried Sampler",
    descripcion:
      "Unión de Jalapeño Poppers, Cheese Sticks, Mac & Tocino y Onion Rings.",
    precio: 450,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568548/MVP_Fried_Sampler_scpiap.webp",
  },
  {
    id: 32,
    tipo: "Alimentos",
    categoria: "Sides",
    nombre: "Jalapeños a la sal",
    descripcion:
      "Jalapeños toreados con salsa gruesa y acompañados de limón verde",
    precio: 60,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568548/Jalapenos_Sal_hpszmn.webp",
  },
  {
    id: 33,
    tipo: "Alimentos",
    categoria: "Postres",
    nombre: "French Toast",
    descripcion:
      "Pan francés con tocino, maple, mantequilla y un toque de leche condensada",
    precio: 100,
    imagen: "https://res.cloudinary.com/dzzfmny6q/image/upload/v1678568563/French_Toast_uwk7tj.webp",
  },
];
